name: user_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.0.7
  flutter_secure_storage: ^5.0.2
  jwt_decode: ^0.3.0
  table_calendar: ^3.2.0
  smooth_page_indicator: ^1.2.0
  socket_io_client: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
